$(document).ready(function(){
	$(".owl-carousel").owlCarousel({
		loop:true,
		responsiveClass:true,
		navText: ["<img src='./icons/arrow-left-circle.svg'>","<img src='./icons/arrow-right-circle.svg'>"],
		responsive:{
			0:{
				items:1,
				nav:true
			},
			600:{
				items:2,
				nav:true
			},
			1000:{
				items:2,
				nav:true
			}
		}
	});
});